### ISSUE TITLE
Allow methods for API

### ISSUE THREAD

**Issue by oggy95** [nuls-io/nuls-v2#515]
I've installed NULS WALLET 2.1, but when I try to call getBestBlock or createAccount via JSON-RPC, here's the answer:
```
{
  "success": false,
  "data": {
    "code": "err_0014",
    "msg": "HTTP 405 Method Not Allowed"
  }
}
```
May i need to change something in nuls.cnf, because i didn't find like this in documentation.

**Comment by zhouwei1985** [comment]
maybe you should add Content-Type with application/json;charset=UTF-8 or something.
you can use postman tool, and import the file to test
https://github.com/nuls-io/nuls-v2/blob/master/module/nuls-api/documents/nuls-api_Postman_JSONRPC.json


zhouwei@nuls.io
 
From: oggy95
Date: 2019-10-03 22:40
To: nuls-io/nuls-v2
CC: Subscribed
Subject: [nuls-io/nuls-v2] Allow methods for API (#515)
I've installed NULS WALLET 2.1, but when I try to call getBestBlock or createAccount via JSON-RPC, here's the answer:
{
  "success": false,
  "data": {
    "code": "err_0014",
    "msg": "HTTP 405 Method Not Allowed"
  }
}

May i need to change something in nuls.cnf, because i didn't find like this in documentation.

**Comment by oggy95** [comment]
Oh, I checked, I send the wrong request to the node wallet. In the address row, I didn't write "/jsonrpc".
Thanks for answering.
